config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  resources :images
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :image, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
  validates_attachment :image, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/spreadsheet.rb
class Spreadsheet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_params
      params.require(:image).permit(:image)
    end
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :set_spreadsheet, only: [:show, :edit, :update, :destroy]

  # GET /spreadsheets
  def index
    @spreadsheets = Spreadsheet.all
  end

  # GET /spreadsheets/1
  def show
  end

  # GET /spreadsheets/new
  def new
    @spreadsheet = Spreadsheet.new
  end

  # GET /spreadsheets/1/edit
  def edit
  end

  # POST /spreadsheets
  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)

    if @spreadsheet.save
      redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spreadsheets/1
  def update
    if @spreadsheet.update(spreadsheet_params)
      redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spreadsheets/1
  def destroy
    @spreadsheet.destroy
    redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spreadsheet
      @spreadsheet = Spreadsheet.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spreadsheet_params
      params.require(:spreadsheet).permit(:csv_file)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @users = User.all
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.haml
= simple_form_for(@image) do |f|
  = f.error_notification

  .form-inputs
    = f.input :image

  .form-actions
    = f.button :submit

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %thead
    %tr
      %th Image
      %th
      %th
      %th

  %tbody
    - @images.each do |image|
      %tr
        %td= image.image
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
.panel.panel-default
  .panel-heading
    .row
      .col-xs-6
        %h3.panel-title Test
      .col-xs-6
        %span.panel-title
          =link_to images_path, class: 'pull-right btn btn-xs btn-default' do
            %i.fa.fa-list-alt
            = "All #{controller_name.classify.humanize.pluralize}"
  .panel-body
    %p
      %b Image:
      = @image.image
    .row.text-right
      .col-xs-12
        =link_to edit_image_path, class: 'btn btn-xs btn-primary' do
          %i.fa.fa-pencil
          Edit
        =link_to edit_image_path, class: 'btn btn-xs btn-danger' do
          %i.fa.fa-trash
          Delete

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
- if user_signed_in? && current_user.admin?
  %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{href: '#', 'data-toggle': "dropdown", 'aria-expanded': "false", role: "button"}
            = user_signed_in? ? current_user.display_name : 'Sign in'
            %span.caret
          %ul.dropdown-menu{role: 'menu'}
            = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Basic'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Basic'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/spreadsheets/_form.html.haml
= simple_form_for(@spreadsheet) do |f|
  = f.error_notification

  .form-inputs
    = f.input :csv_file

  .form-actions
    = f.button :submit

app/views/spreadsheets/edit.html.haml
%h1 Editing spreadsheet

= render 'form'

= link_to 'Show', @spreadsheet
\|
= link_to 'Back', spreadsheets_path

app/views/spreadsheets/index.html.haml
%h1 Listing spreadsheets

%table
  %thead
    %tr
      %th Csv file
      %th
      %th
      %th

  %tbody
    - @spreadsheets.each do |spreadsheet|
      %tr
        %td= spreadsheet.csv_file
        %td= link_to 'Show', spreadsheet
        %td= link_to 'Edit', edit_spreadsheet_path(spreadsheet)
        %td= link_to 'Destroy', spreadsheet, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Spreadsheet', new_spreadsheet_path

app/views/spreadsheets/new.html.haml
%h1 New spreadsheet

= render 'form'

= link_to 'Back', spreadsheets_path

app/views/spreadsheets/show.html.haml
%p#notice= notice

%p
  %b Csv file:
  = @spreadsheet.csv_file

= link_to 'Edit', edit_spreadsheet_path(@spreadsheet)
\|
= link_to 'Back', spreadsheets_path

app/views/users/_user.html.haml
%td= link_to user.name, user
%td= link_to user.email, user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/index.html.haml
/ Page Content
.container
  .row
    .col-lg-12.text-center
      %h1 Welcome
  / /.row
/ /.container